#![cfg_attr(rustfmt, rustfmt_skip)] //skip cargo fmt on autogenerated file

extern crate scheduler;
use scheduler::technical::technical::Input;
use scheduler::models::calendar;

/// AUTO-GENERATED FILE. Do not change.
/// Will be overwritten on build. Edit the file in build_templates or change test generation in build.rs

