#!/usr/bin/env bash

set -au   

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
LOG_BASE="${SCRIPT_DIR}/../_logs"
ZIN_BASE="${SCRIPT_DIR}/../Cargo.toml"

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
    echo "Usage: $0 [PARAM]"
    echo ""
    echo "  PARAM: [Optional] add test case name to be passed to cargo test"
    echo ""
    echo "Example: $0 my_test_case"
    echo "  Runs the cargo test command with the 'my_test_case' parameter"
    echo "  and saves the output to a log file in the _logs directory."
    echo ""
    exit 0
fi

PARAM=${1:-""}
CARGO_MANIFEST_DIR=$ZIN_BASE

CURRENTDATE=$(date +"%Y-%m-%d--%H-%M")
FILE_NAME="test_${PARAM}_${CURRENTDATE}.log"
LOG_FILE="${LOG_BASE}/${FILE_NAME}"
touch "$LOG_FILE"

cargo test --manifest-path "$ZIN_BASE" "$PARAM" > "$LOG_FILE"