name: Deno

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install wasm-bindgen
        run: cargo install wasm-bindgen-cli

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Run tests
        run: ./scripts/deno_test.sh
