name: Test (JS)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run linter
        run: deno lint

      - name: Install wabt
        run: |
          set -e
          curl -L https://github.com/WebAssembly/wabt/releases/download/1.0.13/wabt-1.0.13-linux.tar.gz | tar xzf -
          echo "`pwd`/wabt-1.0.13" > $GITHUB_PATH
      - name: Install binaryen
        run: |
          set -e
          curl -L https://github.com/WebAssembly/binaryen/releases/download/1.39.1/binaryen-1.39.1-x86_64-linux.tar.gz | tar xzf -
          echo "`pwd`/binaryen-1.39.1" > $GITHUB_PATH

      - name: Install wasm-bindgen
        run: cargo install wasm-bindgen-cli

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Run tests
        run: ./test.sh
